spring:
  application:
    name: user-service
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
  datasource:
    url: ${PG_DATASOURCE_URL}
    username: ${PG_USERNAME}
    password: ${PG_PASSWORD}
  cloud:
    loadbalancer:
      enabled: true
server:
  port: ${PORT:0}
eureka:
  server:
    username: ${EUREKA_DISCOVERY_USERNAME}
    password: ${EUREKA_DISCOVERY_PASSWORD}
  client:
    hostname: ${EUREKA_CLIENT_HOSTNAME}
    service-url:
      defaultZone: http://${eureka.server.username}:${eureka.server.password}@${eureka.client.hostname}:8001/eureka
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 10 #send heartbeat every 10 seconds
    leaseExpirationDurationInSeconds: 30 #instance will be marked as unresponsive after 30 seconds
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
jwt:
  token: ${JWT_SECRET_TOKEN}
