spring:
  application:
    name: user-service
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/tinyurl
    username: adityasawant
    password: S@10dulkar
  cloud:
    loadbalancer:
      enabled: true
server:
  port: ${PORT:0}
gateway:
  ip: 192.168.0.0/16
eureka:
  server:
    username: "u"
    password: "p"
  client:
    hostname: localhost
    service-url:
      defaultZone: http://${eureka.server.username}:${eureka.server.password}@${eureka.client.hostname}:8001/eureka
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 10 #send heartbeat every 10 seconds
    leaseExpirationDurationInSeconds: 30 #instance will be marked as unresponsive after 30 seconds
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
jwt:
  token: w6hzSySbh/S1Wv0vZ4BIAfJll1RyxHn/1p05H75PXFY3tQusOkpoa5IQkSgReONSuTnC7b4aEc5UVFiIHmKIig==
