spring:
  profile:
    active: dev
  application:
    name: discovery-service
server:
  port: 7001
tinyurl:
  api:
    url: "www.tinyurl.com"

eureka:
  server:
    username: ${EUREKA_DISCOVERY_USERNAME}
    password: ${EUREKA_DISCOVERY_PASSWORD}
  client:
    register-with-eureka: false
    fetch-registry: false
    hostname: ${EUREKA_CLIENT_HOSTNAME}
    service-url:
      defaultZone: http://${eureka.client.hostname}:${server.port}/eureka
#  server:
#    enable-self-preservation: false
logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF
